// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: barcode.proto

package object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BarcodeServiceClient is the client API for BarcodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BarcodeServiceClient interface {
	Generate(ctx context.Context, in *BarcodeGenerateReq, opts ...grpc.CallOption) (*BarcodeGenerateRes, error)
}

type barcodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBarcodeServiceClient(cc grpc.ClientConnInterface) BarcodeServiceClient {
	return &barcodeServiceClient{cc}
}

func (c *barcodeServiceClient) Generate(ctx context.Context, in *BarcodeGenerateReq, opts ...grpc.CallOption) (*BarcodeGenerateRes, error) {
	out := new(BarcodeGenerateRes)
	err := c.cc.Invoke(ctx, "/object_builder_service.BarcodeService/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BarcodeServiceServer is the server API for BarcodeService service.
// All implementations must embed UnimplementedBarcodeServiceServer
// for forward compatibility
type BarcodeServiceServer interface {
	Generate(context.Context, *BarcodeGenerateReq) (*BarcodeGenerateRes, error)
	mustEmbedUnimplementedBarcodeServiceServer()
}

// UnimplementedBarcodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBarcodeServiceServer struct {
}

func (UnimplementedBarcodeServiceServer) Generate(context.Context, *BarcodeGenerateReq) (*BarcodeGenerateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedBarcodeServiceServer) mustEmbedUnimplementedBarcodeServiceServer() {}

// UnsafeBarcodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BarcodeServiceServer will
// result in compilation errors.
type UnsafeBarcodeServiceServer interface {
	mustEmbedUnimplementedBarcodeServiceServer()
}

func RegisterBarcodeServiceServer(s grpc.ServiceRegistrar, srv BarcodeServiceServer) {
	s.RegisterService(&BarcodeService_ServiceDesc, srv)
}

func _BarcodeService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BarcodeGenerateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarcodeServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.BarcodeService/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarcodeServiceServer).Generate(ctx, req.(*BarcodeGenerateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BarcodeService_ServiceDesc is the grpc.ServiceDesc for BarcodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BarcodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "object_builder_service.BarcodeService",
	HandlerType: (*BarcodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _BarcodeService_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "barcode.proto",
}
