// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: click.proto

package payment_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClickLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId     string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Price       int32  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	ProductId   string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductType string `protobuf:"bytes,4,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	Lang        string `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang,omitempty"`
	RedirectUrl string `protobuf:"bytes,6,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
}

func (x *ClickLinkRequest) Reset() {
	*x = ClickLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_click_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickLinkRequest) ProtoMessage() {}

func (x *ClickLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_click_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickLinkRequest.ProtoReflect.Descriptor instead.
func (*ClickLinkRequest) Descriptor() ([]byte, []int) {
	return file_click_proto_rawDescGZIP(), []int{0}
}

func (x *ClickLinkRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ClickLinkRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ClickLinkRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ClickLinkRequest) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *ClickLinkRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *ClickLinkRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type ClickLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *ClickLinkResponse) Reset() {
	*x = ClickLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_click_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickLinkResponse) ProtoMessage() {}

func (x *ClickLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_click_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickLinkResponse.ProtoReflect.Descriptor instead.
func (*ClickLinkResponse) Descriptor() ([]byte, []int) {
	return file_click_proto_rawDescGZIP(), []int{1}
}

func (x *ClickLinkResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type ClickLinkSvodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId      string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Price        int32  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	ProductId    string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductType  string `protobuf:"bytes,4,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	Lang         string `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang,omitempty"`
	RedirectUrl  string `protobuf:"bytes,6,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	TariffId     string `protobuf:"bytes,7,opt,name=tariff_id,json=tariffId,proto3" json:"tariff_id,omitempty"`
	TariffPeriod string `protobuf:"bytes,8,opt,name=tariff_period,json=tariffPeriod,proto3" json:"tariff_period,omitempty"`
}

func (x *ClickLinkSvodRequest) Reset() {
	*x = ClickLinkSvodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_click_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickLinkSvodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickLinkSvodRequest) ProtoMessage() {}

func (x *ClickLinkSvodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_click_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickLinkSvodRequest.ProtoReflect.Descriptor instead.
func (*ClickLinkSvodRequest) Descriptor() ([]byte, []int) {
	return file_click_proto_rawDescGZIP(), []int{2}
}

func (x *ClickLinkSvodRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ClickLinkSvodRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ClickLinkSvodRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ClickLinkSvodRequest) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *ClickLinkSvodRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *ClickLinkSvodRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *ClickLinkSvodRequest) GetTariffId() string {
	if x != nil {
		return x.TariffId
	}
	return ""
}

func (x *ClickLinkSvodRequest) GetTariffPeriod() string {
	if x != nil {
		return x.TariffPeriod
	}
	return ""
}

type ClickLinkSvodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *ClickLinkSvodResponse) Reset() {
	*x = ClickLinkSvodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_click_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClickLinkSvodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickLinkSvodResponse) ProtoMessage() {}

func (x *ClickLinkSvodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_click_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickLinkSvodResponse.ProtoReflect.Descriptor instead.
func (*ClickLinkSvodResponse) Descriptor() ([]byte, []int) {
	return file_click_proto_rawDescGZIP(), []int{3}
}

func (x *ClickLinkSvodResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

var File_click_proto protoreflect.FileDescriptor

var file_click_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x10, 0x43, 0x6c, 0x69, 0x63,
	0x6b, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x61, 0x6e, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x22,
	0x82, 0x02, 0x0a, 0x14, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x76, 0x6f,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x61, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12,
	0x21, 0x0a, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55,
	0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x5f, 0x69, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x49, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x50, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x22, 0x2b, 0x0a, 0x15, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x4c, 0x69, 0x6e,
	0x6b, 0x53, 0x76, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e,
	0x6b, 0x32, 0xba, 0x01, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4e, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6c,
	0x69, 0x63, 0x6b, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1a, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x43,
	0x6c, 0x69, 0x63, 0x6b, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5a, 0x0a, 0x15, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6c,
	0x69, 0x63, 0x6b, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x76, 0x6f, 0x64, 0x12, 0x1e, 0x2e, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x4c, 0x69, 0x6e, 0x6b,
	0x53, 0x76, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x4c, 0x69, 0x6e, 0x6b,
	0x53, 0x76, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1a,
	0x5a, 0x18, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_click_proto_rawDescOnce sync.Once
	file_click_proto_rawDescData = file_click_proto_rawDesc
)

func file_click_proto_rawDescGZIP() []byte {
	file_click_proto_rawDescOnce.Do(func() {
		file_click_proto_rawDescData = protoimpl.X.CompressGZIP(file_click_proto_rawDescData)
	})
	return file_click_proto_rawDescData
}

var file_click_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_click_proto_goTypes = []interface{}{
	(*ClickLinkRequest)(nil),      // 0: payments.ClickLinkRequest
	(*ClickLinkResponse)(nil),     // 1: payments.ClickLinkResponse
	(*ClickLinkSvodRequest)(nil),  // 2: payments.ClickLinkSvodRequest
	(*ClickLinkSvodResponse)(nil), // 3: payments.ClickLinkSvodResponse
}
var file_click_proto_depIdxs = []int32{
	0, // 0: payments.ClickService.GenerateClickLink:input_type -> payments.ClickLinkRequest
	2, // 1: payments.ClickService.GenerateClickLinkSvod:input_type -> payments.ClickLinkSvodRequest
	1, // 2: payments.ClickService.GenerateClickLink:output_type -> payments.ClickLinkResponse
	3, // 3: payments.ClickService.GenerateClickLinkSvod:output_type -> payments.ClickLinkSvodResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_click_proto_init() }
func file_click_proto_init() {
	if File_click_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_click_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_click_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_click_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickLinkSvodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_click_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClickLinkSvodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_click_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_click_proto_goTypes,
		DependencyIndexes: file_click_proto_depIdxs,
		MessageInfos:      file_click_proto_msgTypes,
	}.Build()
	File_click_proto = out.File
	file_click_proto_rawDesc = nil
	file_click_proto_goTypes = nil
	file_click_proto_depIdxs = nil
}
