// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: order.proto

package payment_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	Create(ctx context.Context, in *CreatePurchaseRequest, opts ...grpc.CallOption) (*CreatePurchaseResponse, error)
	CreateSvodOrder(ctx context.Context, in *CreatePurchaseSvodRequest, opts ...grpc.CallOption) (*CreatePurchaseSvodResponse, error)
	Get(ctx context.Context, in *GetPurchaseRequest, opts ...grpc.CallOption) (*GetPurchaseResponse, error)
	GetSvodOrder(ctx context.Context, in *GetPurchaseRequest, opts ...grpc.CallOption) (*GetPurchaseSvodResponse, error)
	GetList(ctx context.Context, in *GetPurchaseListRequest, opts ...grpc.CallOption) (*GetPurchaseListResponse, error)
	GetSvodOrderList(ctx context.Context, in *GetPurchaseListRequest, opts ...grpc.CallOption) (*GetPurchaseSvodListResponse, error)
	CheckHasAccess(ctx context.Context, in *CheckHasAccessRequest, opts ...grpc.CallOption) (*CheckHasAccessResponse, error)
	UpdateOrderType(ctx context.Context, in *UpdateOrderTypeRequest, opts ...grpc.CallOption) (*CustomEmpty, error)
	UpdateTariffOrderType(ctx context.Context, in *UpdateOrderTypeRequest, opts ...grpc.CallOption) (*CustomEmpty, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) Create(ctx context.Context, in *CreatePurchaseRequest, opts ...grpc.CallOption) (*CreatePurchaseResponse, error) {
	out := new(CreatePurchaseResponse)
	err := c.cc.Invoke(ctx, "/payments.OrderService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CreateSvodOrder(ctx context.Context, in *CreatePurchaseSvodRequest, opts ...grpc.CallOption) (*CreatePurchaseSvodResponse, error) {
	out := new(CreatePurchaseSvodResponse)
	err := c.cc.Invoke(ctx, "/payments.OrderService/CreateSvodOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) Get(ctx context.Context, in *GetPurchaseRequest, opts ...grpc.CallOption) (*GetPurchaseResponse, error) {
	out := new(GetPurchaseResponse)
	err := c.cc.Invoke(ctx, "/payments.OrderService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetSvodOrder(ctx context.Context, in *GetPurchaseRequest, opts ...grpc.CallOption) (*GetPurchaseSvodResponse, error) {
	out := new(GetPurchaseSvodResponse)
	err := c.cc.Invoke(ctx, "/payments.OrderService/GetSvodOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetList(ctx context.Context, in *GetPurchaseListRequest, opts ...grpc.CallOption) (*GetPurchaseListResponse, error) {
	out := new(GetPurchaseListResponse)
	err := c.cc.Invoke(ctx, "/payments.OrderService/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetSvodOrderList(ctx context.Context, in *GetPurchaseListRequest, opts ...grpc.CallOption) (*GetPurchaseSvodListResponse, error) {
	out := new(GetPurchaseSvodListResponse)
	err := c.cc.Invoke(ctx, "/payments.OrderService/GetSvodOrderList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CheckHasAccess(ctx context.Context, in *CheckHasAccessRequest, opts ...grpc.CallOption) (*CheckHasAccessResponse, error) {
	out := new(CheckHasAccessResponse)
	err := c.cc.Invoke(ctx, "/payments.OrderService/CheckHasAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateOrderType(ctx context.Context, in *UpdateOrderTypeRequest, opts ...grpc.CallOption) (*CustomEmpty, error) {
	out := new(CustomEmpty)
	err := c.cc.Invoke(ctx, "/payments.OrderService/UpdateOrderType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateTariffOrderType(ctx context.Context, in *UpdateOrderTypeRequest, opts ...grpc.CallOption) (*CustomEmpty, error) {
	out := new(CustomEmpty)
	err := c.cc.Invoke(ctx, "/payments.OrderService/UpdateTariffOrderType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility
type OrderServiceServer interface {
	Create(context.Context, *CreatePurchaseRequest) (*CreatePurchaseResponse, error)
	CreateSvodOrder(context.Context, *CreatePurchaseSvodRequest) (*CreatePurchaseSvodResponse, error)
	Get(context.Context, *GetPurchaseRequest) (*GetPurchaseResponse, error)
	GetSvodOrder(context.Context, *GetPurchaseRequest) (*GetPurchaseSvodResponse, error)
	GetList(context.Context, *GetPurchaseListRequest) (*GetPurchaseListResponse, error)
	GetSvodOrderList(context.Context, *GetPurchaseListRequest) (*GetPurchaseSvodListResponse, error)
	CheckHasAccess(context.Context, *CheckHasAccessRequest) (*CheckHasAccessResponse, error)
	UpdateOrderType(context.Context, *UpdateOrderTypeRequest) (*CustomEmpty, error)
	UpdateTariffOrderType(context.Context, *UpdateOrderTypeRequest) (*CustomEmpty, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (UnimplementedOrderServiceServer) Create(context.Context, *CreatePurchaseRequest) (*CreatePurchaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedOrderServiceServer) CreateSvodOrder(context.Context, *CreatePurchaseSvodRequest) (*CreatePurchaseSvodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSvodOrder not implemented")
}
func (UnimplementedOrderServiceServer) Get(context.Context, *GetPurchaseRequest) (*GetPurchaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedOrderServiceServer) GetSvodOrder(context.Context, *GetPurchaseRequest) (*GetPurchaseSvodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSvodOrder not implemented")
}
func (UnimplementedOrderServiceServer) GetList(context.Context, *GetPurchaseListRequest) (*GetPurchaseListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedOrderServiceServer) GetSvodOrderList(context.Context, *GetPurchaseListRequest) (*GetPurchaseSvodListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSvodOrderList not implemented")
}
func (UnimplementedOrderServiceServer) CheckHasAccess(context.Context, *CheckHasAccessRequest) (*CheckHasAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHasAccess not implemented")
}
func (UnimplementedOrderServiceServer) UpdateOrderType(context.Context, *UpdateOrderTypeRequest) (*CustomEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderType not implemented")
}
func (UnimplementedOrderServiceServer) UpdateTariffOrderType(context.Context, *UpdateOrderTypeRequest) (*CustomEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTariffOrderType not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.OrderService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).Create(ctx, req.(*CreatePurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CreateSvodOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePurchaseSvodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateSvodOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.OrderService/CreateSvodOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateSvodOrder(ctx, req.(*CreatePurchaseSvodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.OrderService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).Get(ctx, req.(*GetPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetSvodOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetSvodOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.OrderService/GetSvodOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetSvodOrder(ctx, req.(*GetPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPurchaseListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.OrderService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetList(ctx, req.(*GetPurchaseListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetSvodOrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPurchaseListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetSvodOrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.OrderService/GetSvodOrderList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetSvodOrderList(ctx, req.(*GetPurchaseListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CheckHasAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHasAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CheckHasAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.OrderService/CheckHasAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CheckHasAccess(ctx, req.(*CheckHasAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_UpdateOrderType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).UpdateOrderType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.OrderService/UpdateOrderType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).UpdateOrderType(ctx, req.(*UpdateOrderTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_UpdateTariffOrderType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).UpdateTariffOrderType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payments.OrderService/UpdateTariffOrderType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).UpdateTariffOrderType(ctx, req.(*UpdateOrderTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payments.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _OrderService_Create_Handler,
		},
		{
			MethodName: "CreateSvodOrder",
			Handler:    _OrderService_CreateSvodOrder_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _OrderService_Get_Handler,
		},
		{
			MethodName: "GetSvodOrder",
			Handler:    _OrderService_GetSvodOrder_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _OrderService_GetList_Handler,
		},
		{
			MethodName: "GetSvodOrderList",
			Handler:    _OrderService_GetSvodOrderList_Handler,
		},
		{
			MethodName: "CheckHasAccess",
			Handler:    _OrderService_CheckHasAccess_Handler,
		},
		{
			MethodName: "UpdateOrderType",
			Handler:    _OrderService_UpdateOrderType_Handler,
		},
		{
			MethodName: "UpdateTariffOrderType",
			Handler:    _OrderService_UpdateTariffOrderType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
